### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by equinox0815** [realraum/noc#3]
What is the plan of this repo?

- Keep Issues?
- build mono-repo for all the noc stuff (please don't!!!!)
- Just for docs, why not use the already existing repo?

**Comment by equinox0815** [comment]
Just to make things clear. I'm not really against most of this but please document the idea behind things like this repo so we all know what it should be used for and what not. Of course a face2face discussion about core principles like that would be great but this is sadly unrealistic...

**Comment by nbraud** [comment]
@equinox0815 This is literally a mirror of `git.realraum.at:noc`.
You'll notice that I pushed the branches I made to both repos (actually, I set multiple push URLs for my `origin` remote, so I can't not do it).

@gebi and I wanted to work on some Ansible automation and weren't aware of `git.realraum.at:ansible`, so we worked in the `noc` repo; as I said in #1, I think it makes sense to have the NOCs documentation (lacking as it currently is) and the Ansible scripts in the same repo, so the documentation update can be part of the same branch as the corresponding playbook/role update.

**Comment by equinox0815** [comment]
@nbraud: Ok, shall the repo be kept in sync with git.realraum.at? aka shall we pull and push to both repos? Who has commit access to this repo? How do we handle pull requests? Shall any change be done via pull requests which must be merged by someone else than the author of the PR? Is this intended to be an official issue tracker for people outside of noc?
It would be great if we could answer all these questions (and probably more) via the README.md of the repo...

**Comment by nbraud** [comment]
This got clarified in README.md, and nobody opened Github issues in response to the mail on `noc@`
