### ISSUE TITLE
put floppyphone into IOT-like VLAN

### ISSUE THREAD

**Issue by btittelbach** [realraum/noc#65]
Floppyphone (EventPhone SIP with Hackerspace Number 1003, organized by fg, solves current "is someone in the space" problem) is currently using DHCP and NAT and connected to LAN port 10.

Maybe consider putting in separate VLAN where it can be properly firewalled while still having access to external eventphone SIP server.

**Comment by equinox0815** [comment]
IOT VLAN would be wrong because in the final state this VLAN won't have internet access. It should either go into SVC or PUB once this is set up. For now DHCP is fine.

**Comment by btittelbach** [comment]
yes, but i was not aware where I could look up the names of the other planned VLANs

**Comment by equinox0815** [comment]
https://noc.realraum.at/Network.html

**Comment by btittelbach** [comment]
floppyphone was removed
