### ISSUE TITLE
würfel YouTube doesn't work

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [realraum/noc#71]
YouTube buffers 30 minutes and shows the first video frame, buffers again, listening to Music or watching Videos has not been possible in the past 60+ days.

Maybe use UPC for machines that really need to be online and use the other experimental networks like mur.at or funkfeuer for not-so-important ones?

**Comment by peterpoetzi** [comment]
I can confirm that youtube does not work for many months now. Please use UPC uplink for that device.

**Comment by equinox0815** [comment]
I will be at realraum tomorrow evening and take a look at it. But i doubt it has something to do with the internet upstream.

**Comment by equinox0815** [comment]
It was an issue with IPv6. Since i don't have the time to debug the problem i deactivted IPv6 for this host and all other machines that use it.
