### ISSUE TITLE
athsdisc.realraum.at is running debian jessie

### ISSUE THREAD

**Issue by btittelbach** [realraum/noc#75]
`athsdisc.realraum.at` braucht ein Upgrade.

- afaik läuft da nur discourse.hackerspace.at drauf, kann mich aber irren
- ich könnt das Ding natürlich einfach mal auf das nächste Debian hochziehen, hab aber keinen Überblick über sonstige Nebeneffekte, speziell laufen da von @equinox0815 ein paar Prozesse

Input? Warnungen? Freiwillige? ;-)

**Comment by equinox0815** [comment]
Die VM ist und war immer exkulsiv für `discorse.hackerspaces.at`. Der Deal war dass das r3 NOC die VM initial installiert und ab dann nur noch einfache Sicherheitsupdates (also alles was mit apt update/upgrade daherkommt) macht. Upgrades der Applikations Container und System Release Upgrades haben wir bewusst davon ausgenommen.

Die Prozesse die du meinst sind nicht von mir aber weil die innerhalb von Docker laufen und im Container offenbar die UID 1000 haben schaut es von aussen so aus als ob die meinem User gehören.

**Comment by btittelbach** [comment]
- upgraded to bullseye
- upgraded to latest discourse

# verbleibende probleme
bullseye, docker 17.05, systemd 247 und cgroupsv2

nach einem `systemctl stop docker`, `cgroupsfs-umount`, `cgroupsfs-mount`, `systemctl start docker` läuft zwar alles, aber so sollte das nicht sein.

**Comment by btittelbach** [comment]
fixed
